#!/usr/bin/env bash
set -e

cd "${BASH_SOURCE[0]%/*}"
nice rsync --partial --progress --delete --sparse --archive --no-owner --no-perms --no-group --chmod=ugo=rwX target/homepage-GIT-SNAPSHOT.war lyndir.com:jetty/webapps
