# Site settings
title: Maarten Billemont
email: lhunath@lyndir.com
description: >
  Maarten Billemont is a software developer, security analyst and enthusiast.
baseurl: ""
url: "http://lhunath.com"
twitter_username: lhunath
github_username:  lhunath

# Build settings
markdown: kramdown
